---
# 1. Prepare all nodes
- name: Prepare System
  hosts: all
  become: true
  roles:
    - common
  tags: ["prepare"]

# 2. Setup the Control Plane
- name: Setup K3s Master
  hosts: master
  become: true
  roles:
    - k3s_master
  tags: ["k3s_master"]

# 3. Join the Workers
- name: Setup K3s Workers
  hosts: node
  become: true
  roles:
    - k3s_worker
  tags: ["k3s_worker"]

# 4. Install Tailscale on Vault server
- name: Setup Tailscale
  hosts: vault
  become: true
  roles:
    - tailscale
  tags: ["tailscale"]

# 5. Setup Vault Server
- name: Setup Vault Server
  hosts: vault
  become: true
  roles:
    - vault_server
  tags: ["vault"]

# 6. Setup GitHub Runner
- name: Setup GitHub Runner
  hosts: runner
  become: true
  roles:
    - github_runner
  tags: ["github_runner"]